name: Publish Helm Chart to Google Artifact Registry

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: my-pro-417700
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.7.0'  # Adjust the Helm version as needed

      - name: Package Helm chart
        run: |
          helm package app-chart/ -d packaged
        working-directory: ${{ github.workspace }}

      - name: Authenticate with Google Artifact Registry
        run: |
          gcloud auth configure-docker -q
          gcloud auth list

      - name: Tag and Push Helm chart to Google Artifact Registry
        run: |
          chart_file=$(ls packaged/*.tgz)
          gcloud auth configure-docker eu.gcr.io
          helm push hello-chart-0.1.0.tgz oci://us-central1-docker.pkg.dev/my-pro-417700/quickstart-helm-repo