name: Helm package and push to GAR

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: my-pro-417700
  REGISTRY_LOCATION: us-central1
  REPOSITORY: my-chart

jobs:
  package-and-push:
    name: Package and Push Helm Chart
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v4

    - name: Package Helm chart
      run: |
          helm package app-chart/ -d packaged
      working-directory: ${{ github.workspace }}

    - name: Install Helm plugin
      run: |
        helm plugin install https://github.com/chartmuseum/helm-push

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
          project_id: my-pro-417700
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

    - name: Helm login to GAR
      run: |
        gcloud auth configure-docker ${REGISTRY_LOCATION}-docker.pkg.dev --quiet

    - name: Push Helm chart to repository
      run: |
        helm push packaged-charts/*.tgz oci://us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/app-chart
